! Title: Macqael Hardallow
! Description: Filter composed of several Allowed domain unlocked with Adblock Plus Syntax for DNS.
! Version: 3.5
! Homepage: https://github.com/macqael/AdGuard-Home-Filters
! License: https://github.com/macqael/AdGuard-Home-Filters/blob/main/LICENSE
! Last modified: 2021-05-02
@@||googleusercontent.com^
@@||storage.googleapis.com^
@@||googlevideo.com^
@@||ggpht.com^
@@||content-storage-download.googleapis.com^
@@||docs.google.com^
@@||*._dns-sd._udp.*.in-addr.arpa^
@@||*.ip6.arpa^
@@||ipv4only.arpa^
@@||yimg.com^
@@||youtu.be^
@@||youtube-nocookie.com^
@@||youtube.com^
@@||wikihow.com^
@@||wikimedia.org^
@@||wikipedia.com^
@@||wikipedia.org^
@@||ocsp.sectigo.com^
@@||smoot.apple.com^
@@||licdn.com^
@@||pinimg.com^
@@||api.swiftype.com^
@@|token.safebrowsing.apple^
@@|safebrowsing.g.aaplimg.com
@@|track.bpost.cloud^
@@|weekend.levif.be^
@@|l.facebook.com^
@@|wordpress.com^
@@|wordpress.org^
@@|r3.o.lencr.org^
@@|ocsp.pki.goog^
@@|crl.pki.goog^
@@|youtube-ui.l.google.com^
@@|pki-goog.l.google.com^
@@|googleapis.l.google.com^
@@|clients.l.google.com^
@@|cdn.ravenjs.com^
@@|ajax.googleapis.com^
@@|ghs.googlehosted.com^
@@|storage.cloud.google.com^
@@|cloudstorage.gog.com^
@@|www.gstatic.com^
@@|www.google.com^
@@|csp.withgoogle.com^
@@|youtubei.googleapis.com^
@@|video.google.com^
@@|upload.wikimedia.org^
@@|znn6.mjt.lu^
@@|update.videolan.org^
@@||gvt1.com^
@@|apis.google.com^
@@|mtalk.google.com^
@@|www.googleapis.com^
@@|*-mtalk.google.com^
@@||cloudfront.net^
@@||ytimg.com^
@@|0.wikipedia.com^
@@|1fichier.com^
@@|ac.duckduckgo.com^
@@|account.adguard.com^
@@|adguard.com^
@@|akadns.net^
@@|akamai.net^
@@|akamaiedge.net^
@@|akamaihd.net^
@@|akamaitechnologies.com^
@@|akamaized.net^
@@|albert.apple.com^
@@|alternativeto.net^
@@|amd.com^
@@|api-da.wixmp.com^
@@|api-glb.smoot.apple.com^
@@|api-m.paypal.com^
@@|api.adguard.com^
@@|api.feedburner.com^
@@|api.github.com^
@@|api.nuget.org^
@@|api.paypal.com^
@@|api.steampowered.com^
@@|api.weather.com^
@@|api1.weather.com^
@@|api2.weather.com^
@@|api3.weather.com^
@@|appldnld.apple.com^
@@|apple.com^
@@|appleid.apple.com^
@@|assets-cdn.github.com^
@@|assets.gitlab-static.net^
@@|avatars*.githubusercontent.com^
@@|avatars0.githubusercontent.com^
@@|avatars1.githubusercontent.com^
@@|avatars2.githubusercontent.com^
@@|avatars3.githubusercontent.com^
@@|ax.init.itunes.apple.com^
@@|ax.itunes.apple.com^
@@|b.stats.paypal.com^
@@|b.tiles.mapbox.com^
@@|cacerts.digicert.com^
@@|caldav.fe.apple-dns.net^
@@|caldav.icloud.com^
@@|calendars.fe.apple-dns.net^
@@|camo.githubusercontent.com^
@@|cdn.cloudflare.net^
@@|cdn.cloudflare.steamstatic.com^
@@|cdn.discordapp.com^
@@|cdn.flowplayer.com^
@@|cdn.jsdelivr.net^
@@|cdnjs.cloudflare.com^
@@|checkout.stripe.com^
@@|client-download.steampowered.com^
@@|client.teamviewer.com^
@@|clientconfig.akamai.steamstatic.com^
@@|cloudflare.com^
@@|code.jquery.com^
@@|collector.githubapp.com^
@@|commons.wikipedia.com^
@@|community.akamai.steamstatic.com^
@@|community.cloudflare.steamstatic.com^
@@|configuration.apple.com.akadns.net^
@@|content.cloudflare.com^
@@|creativecommons.org^
@@|crl.comodoca.com^
@@|crl.comodoca4.com^
@@|crl.entrust.net^
@@|crl.globalsign.com^
@@|crl.globalsign.net^
@@|crl.identrust.com^
@@|crl.sca1b.amazontrust.com^
@@|crl.thawte.com^
@@|crl.usertrust.com^
@@|crl.verisign.com^
@@|crl4.digicert.com^
@@|cs.wikipedia.com^
@@|curben.gitlab.io^
@@|cy.wikipedia.com^
@@|d3aqoihi2n8ty8.cloudfront.net^
@@|dash.cloudflare.com^
@@|adb.oisd.nl^
@@|dc.services.visualstudio.com^
@@|developer.mozilla.org^
@@|developers.cloudflare.com^
@@|discord.com^
@@|discord.gg^
@@|discordapp.com^
@@|discussions.apple.com^
@@|dl.humble.com^
@@|download.wikipedia.com^
@@|downloads.intercomcdn.com^
@@|drive.google.com^
@@|duckduckgo.com^
@@|en.wikipedia.com^
@@|epicgames.com^
@@|epl.paypal-communication.com^
@@|eu.static.mega.co.nz^
@@|eu.wikipedia.com^
@@|evcs-ocsp.ws.symantec.com^
@@|feedbackws.icloud.com^
@@|feedly.com^
@@|fontawesome-cdn.fonticons.netdna-cdn.com^
@@|fonts.gstatic.com^
@@|fonts.intercomcdn.com^
@@|form.typeform.com^
@@|fr.uptodown.com^
@@|fr.wikipedia.com^
@@|frog.wix.com^
@@|g.static.mega.co.nz^
@@|gist.github.com^
@@|gist.githubusercontent.com^
@@|github-cloud.s3.amazonaws.com^
@@|github-production-release-asset-*.s3.amazonaws.com^
@@|github-production-user-asset-6210df.s3.amazonaws.com^
@@|github.com^
@@|github.io^
@@|gitlab.com^
@@|glb.paypal.com^
@@|go.microsoft.com^
@@|gog-statics.com^
@@|gog.com^
@@|graphql.epicgames.com^
@@|gs.apple.com^
@@|hash.github.com^
@@|hcaptcha.com^
@@|he.wikipedia.com^
@@|heartbeat.dm.origin.com^
@@|history.paypal.com^
@@|humblebundle.com^
@@|i.ibb.co^
@@|i.ytimg.com^
@@|i1.ytimg.com^
@@|id.wikipedia.com^
@@|images-1.discordapp.net^
@@|images-2.discordapp.net^
@@|images-ext-1.discordapp.net^
@@|images-ext-2.discordapp.net^
@@|images.discordapp.net^
@@|img.youtube.com^
@@|ingame-news.ubi.com^
@@|ipv6check-http.steamcontent.com^
@@|ir.ebaystatic.com^
@@|itunes.apple.com^
@@|itunesconnect.apple.com^
@@|ja.wikipedia.com^
@@|jp.wikipedia.com^
@@|js.stripe.com^
@@|kb.adguard.com^
@@|la.wikipedia.com^
@@|letsencrypt.org^
@@|links.duckduckgo.com^
@@|local.adguard.com^
@@|login.windows.net^
@@|logincdn.msauth.net^
@@|lu.api.mega.co.nz^
@@|lv.wikipedia.com^
@@|mail.protonmail.com^
@@|mapbox.com^
@@|maxcdn.bootstrapcdn.com^
@@|media.discordapp.net^
@@|media.steampowered.com^
@@|media4.steampowered.com^
@@|mediafire.com^
@@|mega.co.nz^
@@|mega.io^
@@|mega.nz^
@@|ml.wikipedia.com^
@@|mobile.paypal.com^
@@|mozilla.com^
@@|mozilla.net^
@@|mozilla.org^
@@|naomy.cdntrex.com^
@@|nz.static.mega.co.nz^
@@|ocsp.comodoca.com^
@@|ocsp.comodoca4.com^
@@|ocsp.digicert.com^
@@|ocsp.globalsign.com^
@@|ocsp.godaddy.com^
@@|ocsp.msocsp.com^
@@|ocsp.sca1b.amazontrust.com^
@@|ocsp.sectigo.com^
@@|ocsp.thawte.com^
@@|ocsp.usertrust.com^
@@|ocsp.verisign.com^
@@|ocsp*.globalsign.com^
@@|odinvzc.azureedge.net^
@@|p.ebaystatic.com^
@@|p.typekit.net^
@@|photo.plus.google.com^
@@|pl.wikipedia.com^
@@|polyfill.io^
@@|qos*.ol.epicgames.com^
@@|raw.github.com^
@@|raw.githubusercontent.com^
@@|redirector.gvt1.com^
@@|reports.adguard.com^
@@|repository-images.githubusercontent.com^
@@|rg3.github.io^
@@|rover.ebay.com^
@@|s.youtube.com^
@@|s.ytimg.com^
@@|s2.youtube.com^
@@|script.google.com^
@@|sourceforge.net^
@@|speedtest.net^
@@|spoprod-a.akamaihd.net^
@@|ssl.gstatic.com^
@@|stackexchange.com^
@@|stackoverflow.com^
@@|static-assets-prod.epicgames.com^
@@|static-assets-prod.unrealengine.com^
@@|static.a.upc.ubisoft.com^
@@|static.icloud.com^
@@|static.intercomassets.com^
@@|static.mediafire.com^
@@|static.wikia.nocookie.net^
@@|static.wixstatic.com^
@@|static*.cdn.ubi.com^
@@|static*.ubi.com^
@@|staticcdn.duckduckgo.com^
@@|status.github.com^
@@|steamcommunity.com^
@@|steamstore-a.akamaihd.net^
@@|steamuserimages-a.akamaihd.net^
@@|store.apple.com^
@@|sv.wikipedia.com^
@@|ta.wikipedia.com^
@@|tr.wikipedia.com^
@@|ubisoft-orbit-savegames.s3.amazonaws.com^
@@|ubistatic*-a.akamaihd.net^
@@|udomain.dl.sourceforge.net^
@@||phncdn.com^
@@|pornhub.com^
@@|www.pornhub.com^
@@|fr.pornhub.com^
@@|9hentai.ru^
@@|cdn.9hentai.ru^
@@|lewdpatcher.com^
@@|weeb.hanime.tv^
@@|player3.hanime.tv^
@@|hanime.tv^
@@|hw.hanime.tv^
@@|attachments.f95zone.to^
@@|attachments.f95zone.com^
@@|static.f95zone.to^
@@|static.f95zone.com^
@@|f95zone.to^
@@|f95zone.com^
@@|wallet.ecom.ubi.com^
@@|user-images.githubusercontent.com^
@@|uplaypc-s-ubisoft.cdn.ubi.com^
@@|click.mlsend.com^
@@|feedproxy.google.com^
@@|edge-chat.facebook.com^
@@|sso.roularta.be^
@@|messagent.roulartamail.be^
@@|www.boulevard-voltaire.fr^
@@|www.agoravox.fr^
@@|www.breizh-info.com^
@@|link.huffingtonpost.fr^
@@|www.dreuz.info^
@@|levif.be^
@@|mail.levif.be^
@@|smp-device-content.apple.com^
@@|internalcheck.apple.com^
@@|radarsubmissions.apple.com^
@@|cstat.apple.com^
@@|metrics.icloud.com^
@@|api.mixpanel.com^
@@|m.stripe.network^
@@|stripe.network^
@@|insights-collector.gog.com^
@@|www.paypal.com^
@@|stats.gc.apple.com^
@@|lightstep.medium.systems^
@@|ytimg.l.google.com^
@@|cdn.report-uri.com^
@@|stat.ripe.net^
@@|latency.discord.media^
@@|images2.imgbox.com^
@@|tracking.epicgames.com^
@@|www.bvoltaire.fr^
@@|ipm.emsecure.net^
