! Title: Macqael Hardallow
! Description: Filter composed of several Allowed domain unlocked with Adblock Plus Syntax for DNS.
! Version: 3.1.3
! Homepage: https://github.com/macqael/AdGuard-Home-Filters
! License: https://github.com/macqael/AdGuard-Home-Filters/blob/main/LICENSE
! Last modified: 2021-04-07
@@||googleusercontent.com^$important
@@||storage.googleapis.com^$important
@@||googlevideo.com^$important
@@||ggpht.com^$important
@@||content-storage-download.googleapis.com$important
@@||docs.google.com^$important
@@||*._dns-sd._udp.*.in-addr.arpa^$important
@@||*.ip6.arpa^$important
@@||ipv4only.arpa^$important
@@||yimg.com^$important
@@||youtu.be^$important
@@||youtube-nocookie.com^$important
@@||youtube.com^$important
@@||wikihow.com^$important
@@||wikimedia.org^$important
@@||wikipedia.com^$important
@@||wikipedia.org^$important
@@||ocsp.sectigo.com^$important
@@||smoot.apple.com^$important
@@||licdn.com^$important
@@||pinimg.com^$important
@@||api.swiftype.com^$important
@@||services.msn.com^$important
@@|platform.bing.com^$important
@@|www.download.windowsupdate.com^$important
@@|interact.f5.com^$important
@@|weekend.levif.be^$important
@@|upload.facebook.com^$important
@@|l.facebook.com^$important
@@|wordpress.com^$important
@@|wordpress.org^$important
@@|win10.ipv6.microsoft.com^$important
@@|r3.o.lencr.org^$important
@@|ocsp.pki.goog^$important
@@|crl.pki.goog^$important
@@|youtube-ui.l.google.com^$important
@@|pki-goog.l.google.com^$important
@@|googleapis.l.google.com^$important
@@|clients.l.google.com^$important
@@|safebrowsing.googleapis.com^$important
@@|safebrowsing.google.com^$important
@@|cdn.ravenjs.com^$important
@@|ajax.googleapis.com^$important
@@|ghs.googlehosted.com^$important
@@|storage.cloud.google.com^$important
@@|cloudstorage.gog.com^$important
@@|www.gstatic.com^$important
@@|www.google.com^$important
@@|csp.withgoogle.com^$important
@@|youtubei.googleapis.com^$important
@@|video.google.com^$important
@@|virustotal.com^$important
@@|upload.wikimedia.org^$important
@@|uploaded.net^$important
@@|uptobox.com^$important
@@|update.videolan.org^$important
@@||gvt1.com^$important
@@|play.google.com^$important
@@|play.googleapis.com^$important
@@|update.googleapis.com^$important
@@|android.clients.google.com^$important
@@|android.googleapis.com^$important
@@|apis.google.com^$important
@@|mtalk.google.com^$important
@@|www.googleapis.com^$important
@@|*-dnsotls-ds.metric.gstatic.com^$important
@@|*-mtalk.google.com^$important
@@||aria.microsoft.com^$important
@@||cloudfront.net^$important
@@||delivery.mp.microsoft.com^$important
@@||deviantart.com^$important
@@||gallery.vsassets.io^$important
@@||gallerycdn.vsassets.io^$important
@@||prod.do.dsp.mp.microsoft.com^$important
@@||settings.live.net^$important
@@||update.microsoft.com^$important
@@||wns.windows.com^$important
@@||ytimg.com^$important
@@|0.wikipedia.com^$important
@@|1fichier.com^$important
@@|ac.duckduckgo.com^$important
@@|account.adguard.com^$important
@@|acctcdn.msauth.net^$important
@@|acctcdn.msftauth.net^$important
@@|adguard.com^$important
@@|adl.windows.com^$important
@@|aka.ms^$important
@@|akadns.net^$important
@@|akamai.net^$important
@@|akamaiedge.net^$important
@@|akamaihd.net^$important
@@|akamaitechnologies.com^$important
@@|akamaized.net^$important
@@|albert.apple.com^$important
@@|aldi.com.au^$important
@@|alternativeto.net^$important
@@|amd.com^$important
@@|answers.microsoft.com^$important
@@|api-da.wixmp.com^$important
@@|api-glb.smoot.apple.com^$important
@@|api-m.paypal.com^$important
@@|api.adguard.com^$important
@@|api.bing.com^$important
@@|api.feedburner.com^$important
@@|api.github.com^$important
@@|api.live.net^$important
@@|api.msn.com^$important
@@|api.nuget.org^$important
@@|api.paypal.com^$important
@@|api.steampowered.com^$important
@@|api.weather.com^$important
@@|api1.weather.com^$important
@@|api2.weather.com^$important
@@|api3.weather.com^$important
@@|apis.live.net^$important
@@|app.vsaex.visualstudio.com^$important
@@|appldnld.apple.com^$important
@@|apple.com^$important
@@|appleid.apple.com^$important
@@|assets-cdn.github.com^$important
@@|assets.gitlab-static.net^$important
@@|assets.onestore.ms^$important
@@|au.download.windowsupdate.com^$important
@@|au.v4.download.windowsupdate.com^$important
@@|avatars*.githubusercontent.com^$important
@@|avatars0.githubusercontent.com^$important
@@|avatars1.githubusercontent.com^$important
@@|avatars2.githubusercontent.com^$important
@@|avatars3.githubusercontent.com^$important
@@|ax.init.itunes.apple.com^$important
@@|ax.itunes.apple.com^$important
@@|az667904.vo.msecnd.net^$important
@@|az725175.vo.msecnd.net^$important
@@|az764295.vo.msecnd.net^$important
@@|b.stats.paypal.com^$important
@@|b.tiles.mapbox.com^$important
@@|bing.com^$important
@@|bing.fr^$important
@@|browser.pipe.aria.microsoft.com^$important
@@|c.s-microsoft.com^$important
@@|c1.microsoft.com^$important
@@|cacerts.digicert.com^$important
@@|caldav.fe.apple-dns.net^$important
@@|caldav.icloud.com^$important
@@|calendars.fe.apple-dns.net^$important
@@|camo.githubusercontent.com^$important
@@|cdn.cloudflare.net^$important
@@|cdn.cloudflare.steamstatic.com^$important
@@|cdn.discordapp.com^$important
@@|cdn.flowplayer.com^$important
@@|cdn.jsdelivr.net^$important
@@|cdnjs.cloudflare.com^$important
@@|checkappexec.microsoft.com^$important
@@|checkout.stripe.com^$important
@@|choice.microsoft.com^$important
@@|client-download.steampowered.com^$important
@@|client.teamviewer.com^$important
@@|clientconfig.akamai.steamstatic.com^$important
@@|clients1.google.com^$important
@@|clients2.google.com^$important
@@|clients3.google.com^$important
@@|clients4.google.com^$important
@@|clients5.google.com^$important
@@|clients6.google.com^$important
@@|cloudflare.com^$important
@@|code.jquery.com^$important
@@|collections.md.mp.microsoft.com^$important
@@|collector.githubapp.com^$important
@@|commons.wikipedia.com^$important
@@|community.akamai.steamstatic.com^$important
@@|community.cloudflare.steamstatic.com^$important
@@|configuration.apple.com.akadns.net^$important
@@|content.cloudflare.com^$important
@@|creativecommons.org^$important
@@|crl.comodoca.com^$important
@@|crl.comodoca4.com^$important
@@|crl.entrust.net^$important
@@|crl.globalsign.com^$important
@@|crl.globalsign.net^$important
@@|crl.identrust.com^$important
@@|crl.sca1b.amazontrust.com^$important
@@|crl.thawte.com^$important
@@|crl.usertrust.com^$important
@@|crl.verisign.com^$important
@@|crl4.digicert.com^$important
@@|cs.wikipedia.com^$important
@@|ctldl.windowsupdate.com^$important
@@|curben.gitlab.io^$important
@@|cy.wikipedia.com^$important
@@|cy2.settings.data.microsoft.com.akadns.net^$important
@@|d3aqoihi2n8ty8.cloudfront.net^$important
@@|dash.cloudflare.com^$important
@@|datasert.gallery.vsassets.io^$important
@@|adb.oisd.nl^$important
@@|dc.services.visualstudio.com^$important
@@|developer.mozilla.org^$important
@@|developers.cloudflare.com^$important
@@|developers.google.com^$important
@@|deviantart.com^$important
@@|discord.com^$important
@@|discord.gg^$important
@@|geopolitique-profonde.systeme.io^$important
@@|discordapp.com^$important
@@|discussions.apple.com^$important
@@|displaycatalog.mp.microsoft.com^$important
@@|dl.delivery.mp.microsoft.com^$important
@@|dl.humble.com^$important
@@|dlassets-ssl.xboxlive.com^$important
@@|dmd.metaservices.microsoft.com^$important
@@|dns.msftncsi.com^$important
@@|docs.live.net^$important
@@|download.microsoft.com^$important
@@|download.visualstudio.microsoft.com^$important
@@|download.wikipedia.com^$important
@@|download.windowsupdate.com^$important
@@|downloads.intercomcdn.com^$important
@@|downloads.vivaldi.com^$important
@@|drive.google.com^$important
@@|ds.download.windowsupdate.com^$important
@@|duckduckgo.com^$important
@@|ea.com^$important
@@|edge.microsoft.com^$important
@@|emdl.ws.microsoft.com^$important
@@|emea01.safelinks.protection.outlook.com^$important
@@|en.wikipedia.com^$important
@@|epicgames.com^$important
@@|epl.paypal-communication.com^$important
@@|eu.static.mega.co.nz^$important
@@|eu.vortex.data.microsoft.com.akadns.net^$important
@@|eu.vortex.data.microsoft.com^$important
@@|eu.wikipedia.com^$important
@@|eur01.safelinks.protection.outlook.com^$important
@@|eur02.safelinks.protection.outlook.com^$important
@@|eur03.safelinks.protection.outlook.com^$important
@@|eur04.safelinks.protection.outlook.com^$important
@@|evcs-ocsp.ws.symantec.com^$important
@@|evoke-windowsservices-tas.msedge.net^$important
@@|favorites.live.com^$important
@@|fe2cr.update.microsoft.com^$important
@@|feedbackws.icloud.com^$important
@@|feedly.com^$important
@@|fontawesome-cdn.fonticons.netdna-cdn.com^$important
@@|fonts.gstatic.com^$important
@@|fonts.intercomcdn.com^$important
@@|form.typeform.com^$important
@@|forms.office.com^$important
@@|fpt.microsoft.com^$important
@@|fr.uptodown.com^$important
@@|fr.wikipedia.com^$important
@@|frog.wix.com^$important
@@|fs.microsoft.com^$important
@@|g.live.com^$important
@@|g.static.mega.co.nz^$important
@@|gist.github.com^$important
@@|gist.githubusercontent.com^$important
@@|github-cloud.s3.amazonaws.com^$important
@@|github-production-release-asset-*.s3.amazonaws.com^$important
@@|github-production-user-asset-6210df.s3.amazonaws.com^$important
@@|github.com^$important
@@|github.io^$important
@@|gitlab.com^$important
@@|glb.paypal.com^$important
@@|go.microsoft.com^$important
@@|gog-statics.com^$important
@@|gog.com^$important
@@|graph.microsoft.com^$important
@@|graphql.epicgames.com^$important
@@|gs.apple.com^$important
@@|hash.github.com^$important
@@|hcaptcha.com^$important
@@|he.wikipedia.com^$important
@@|heartbeat.dm.origin.com^$important
@@|history.paypal.com^$important
@@|humblebundle.com^$important
@@|i.ibb.co^$important
@@|i.ytimg.com^$important
@@|i1.ytimg.com^$important
@@|id.wikipedia.com^$important
@@|images-1.discordapp.net^$important
@@|images-2.discordapp.net^$important
@@|images-ext-1.discordapp.net^$important
@@|images-ext-2.discordapp.net^$important
@@|images.discordapp.net^$important
@@|img-prod-cms-rt-microsoft-com.akamaized.net^$important
@@|img.youtube.com^$important
@@|in.appcenter.ms^$important
@@|ingame-news.ubi.com^$important
@@|ipv6check-http.steamcontent.com^$important
@@|ir.ebaystatic.com^$important
@@|itunes.apple.com^$important
@@|itunesconnect.apple.com^$important
@@|ja.wikipedia.com^$important
@@|jcmsfd.account.microsoft.com^$important
@@|jp.pipe.aria.microsoft.com^$important
@@|jp.wikipedia.com^$important
@@|js.stripe.com^$important
@@|kb.adguard.com^$important
@@|la.wikipedia.com^$important
@@|letsencrypt.org^$important
@@|licensing.mp.microsoft.com^$important
@@|links.duckduckgo.com^$important
@@|live.com^$important
@@|live.github.com^$important
@@|local.adguard.com^$important
@@|login.live.com^$important
@@|login.microsoftonline.com^$important
@@|login.windows.net^$important
@@|logincdn.msauth.net^$important
@@|lu.api.mega.co.nz^$important
@@|lv.wikipedia.com^$important
@@|mail.live.com^$important
@@|mail.protonmail.com^$important
@@|mapbox.com^$important
@@|maps.windows.com^$important
@@|maxcdn.bootstrapcdn.com^$important
@@|media.discordapp.net^$important
@@|media.steampowered.com^$important
@@|media4.steampowered.com^$important
@@|mediafire.com^$important
@@|mega.co.nz^$important
@@|mega.io^$important
@@|mega.nz^$important
@@|mem.gfx.ms^$important
@@|microsoftonline.com^$important
@@|ml.wikipedia.com^$important
@@|mobile.paypal.com^$important
@@|mozilla.com^$important
@@|mozilla.net^$important
@@|mozilla.org^$important
@@|msedge.api.cdp.microsoft.com^$important
@@|msftconnecttest.com^$important
@@|msftncsi.com^$important
@@|msn.com^$important
@@|mucp.api.account.microsoft.com^$important
@@|music.plus.google.com^$important
@@|naomy.cdntrex.com^$important
@@|ntp.msn.com^$important
@@|nz.static.mega.co.nz^$important
@@|oauth.live.com^$important
@@|ocsp.comodoca.com^$important
@@|ocsp.comodoca4.com^$important
@@|ocsp.digicert.com^$important
@@|ocsp.globalsign.com^$important
@@|ocsp.godaddy.com^$important
@@|ocsp.msocsp.com^$important
@@|ocsp.sca1b.amazontrust.com^$important
@@|ocsp.sectigo.com^$important
@@|ocsp.thawte.com^$important
@@|ocsp.usertrust.com^$important
@@|ocsp.verisign.com^$important
@@|ocsp*.globalsign.com^$important
@@|odc.officeapps.live.com^$important
@@|odinvzc.azureedge.net^$important
@@|office.com^$important
@@|office.net^$important
@@|office365.com^$important
@@|officeclient.microsoft.com^$important
@@|officehomeblobs.blob.core.windows.net^$important
@@|oneclient.sfx.ms^$important
@@|onedrive.com^$important
@@|onedrive.live.com^$important
@@|oneocsp.microsoft.com^$important
@@|outlook.com^$important
@@|outlook.live.com^$important
@@|outlook.office.com^$important
@@|outlook.office365.com^$important
@@|p.ebaystatic.com^$important
@@|p.sfx.ms^$important
@@|p.typekit.net^$important
@@|partner.microsoft.com^$important
@@|paymentinstruments.mp.microsoft.com^$important
@@|photo.plus.google.com^$important
@@|photos.live.com^$important
@@|pics.ebaystatic.com^$important
@@|pl.wikipedia.com^$important
@@|pmservices.cp.microsoft.com^$important
@@|policies.live.net^$important
@@|polyfill.io^$important
@@|posarprodcssservice.accesscontrol.windows.net^$important
@@|privacy.microsoft.com^$important
@@|products.office.com^$important
@@|protonmail.ch^$important
@@|protonmail.com^$important
@@|pti.store.microsoft.com^$important
@@|purchase.mp.microsoft.com^$important
@@|qcz.gallery.vsassets.io^$important
@@|qos*.ol.epicgames.com^$important
@@|raw.github.com^$important
@@|raw.githubusercontent.com^$important
@@|redemptionservices.accesscontrol.windows.net^$important
@@|redirector.gvt1.com^$important
@@|reports.adguard.com^$important
@@|repository-images.githubusercontent.com^$important
@@|rg3.github.io^$important
@@|ris.api.iris.microsoft.com^$important
@@|rover.ebay.com^$important
@@|s.youtube.com^$important
@@|s.ytimg.com^$important
@@|s2.youtube.com^$important
@@|script.google.com^$important
@@|secureir.ebaystatic.com^$important
@@|self.events.data.microsoft.com^$important
@@|service.weather.microsoft.com^$important
@@|settings-win.data.microsoft.com^$important
@@|settings.data.microsoft.com^$important
@@|settings.live.net^$important
@@|sfdataservice.microsoft.com^$important
@@|slscr.update.microsoft.com^$important
@@|smartscreen-prod.microsoft.com^$important
@@|smartscreen.microsoft.com^$important
@@|snapi.live.net^$important
@@|sourceforge.net^$important
@@|spaces.live.com^$important
@@|speedtest.net^$important
@@|spo-ring.msedge.net^$important
@@|spoprod-a.akamaihd.net^$important
@@|ssl.gstatic.com^$important
@@|stackexchange.com^$important
@@|stackoverflow.com^$important
@@|static-assets-prod.epicgames.com^$important
@@|static-assets-prod.unrealengine.com^$important
@@|static.a.upc.ubisoft.com^$important
@@|static.icloud.com^$important
@@|static.intercomassets.com^$important
@@|static.mediafire.com^$important
@@|static.wikia.nocookie.net^$important
@@|static.wixstatic.com^$important
@@|static*.cdn.ubi.com^$important
@@|static*.ubi.com^$important
@@|staticcdn.duckduckgo.com^$important
@@|statics-*.onestore.ms^$important
@@|status.github.com^$important
@@|steamcommunity.com^$important
@@|steamstore-a.akamaihd.net^$important
@@|steamuserimages-a.akamaihd.net^$important
@@|storage.live.com^$important
@@|storage.msn.com^$important
@@|store-images.microsoft.com^$important
@@|store-images.s-microsoft.com^$important
@@|store.apple.com^$important
@@|storecatalogrevocation.storequality.microsoft.com^$important
@@|storeedgefd.dsx.mp.microsoft.com^$important
@@|support.microsoft.com^$important
@@|sv.wikipedia.com^$important
@@|ta.wikipedia.com^$important
@@|tile-service.weather.microsoft.com^$important
@@|time.windows.com^$important
@@|token.cp.microsoft.com/^$important
@@|tokensit.cp.microsoft-tst.com/^$important
@@|tr.wikipedia.com^$important
@@|tsfe.trafficshaping.dsp.mp.microsoft.com^$important
@@|ubisoft-orbit-savegames.s3.amazonaws.com^$important
@@|ubistatic*-a.akamaihd.net^$important
@@|udomain.dl.sourceforge.net^$important
@@||phncdn.com^$important
@@|pornhub.com^$important
@@|www.pornhub.com^$important
@@|fr.pornhub.com^$important
@@|9hentai.ru^$important
@@|cdn.9hentai.ru^$important
@@|lewdpatcher.com^$important
@@|weeb.hanime.tv^$important
@@|player3.hanime.tv^$important
@@|hanime.tv^$important
@@|hw.hanime.tv^$important
@@|attachments.f95zone.to^$important
@@|attachments.f95zone.com^$important
@@|static.f95zone.to^$important
@@|static.f95zone.com^$important
@@|f95zone.to^$important
@@|f95zone.com^$important
@@|visualstudio-devdiv-c2s.msedge.net^$important
@@|visualstudio.com^$important
@@|wallet.ecom.ubi.com^$important
@@|user-images.githubusercontent.com^$important
@@|uplaypc-s-ubisoft.cdn.ubi.com^$important
@@|update.code.visualstudio.com^$important
@@|click.mlsend.com^$important
@@|feedproxy.google.com^$important
@@|edge-chat.facebook.com^$important
@@|sso.roularta.be^$important
@@|messagent.roulartamail.be^$important
@@|www.bvoltaire.fr^$important
@@|www.boulevard-voltaire.fr^$important
@@|www.agoravox.fr^$important
@@|www.breizh-info.com^$important
@@|link.huffingtonpost.fr^$important
@@|www.dreuz.info^$important
@@|levif.be^$important
@@|mail.levif.be^$important
@@|wcpstatic.microsoft.com^$important
@@|wdcp.microsoft.com^$important
@@|v10.events.data.microsoft.com^$important
@@|v20.events.data.microsoft.com^$important
@@|update.microsoft.com^$important
@@|alive.github.com^$important
@@|smp-device-content.apple.com^$important
@@|internalcheck.apple.com^$important
@@|radarsubmissions.apple.com^$important
@@|cstat.apple.com^$important
@@|code.visualstudio.com^$important
@@|metrics.icloud.com^$important
@@|api.mixpanel.com^$important
@@|m.stripe.network^$important
@@|stripe.network^$important
@@|service.videoplaza.tv^$important
@@|targetemsecure.blob.core.windows.net^$important
@@|config.edge.skype.com^$important
@@|nav.smartscreen.microsoft.com^$important
@@|nf.smartscreen.microsoft.com^$important
@@|aadcdn.msauth.net^$important
@@|js.monitor.azure.com^$important
@@|fp.msedge.net^$important
@@|insights-collector.gog.com^$important
@@|www.paypal.com^$important
@@|stats.gc.apple.com^$important
@@|lightstep.medium.systems^$important
@@|ytimg.l.google.com^$important
@@|cdn.report-uri.com^$important
@@|stat.ripe.net^$important
@@|latency.discord.media^$important
@@|images2.imgbox.com^$important
@@|developer.chrome.com^$important
@@|developers.chrome.com^$important
@@|www.whoer.net^$important^$important
@@|static.asm.skype.com^$important
@@|api3.cc.skype.com^$important
@@|activity.windows.com^$important
@@|consumer.entitlement.skype.com^$important
@@|api.asm.skype.com^$important
@@|people.skype.com^$important
@@|contacts.skype.com^$important
@@|www.msftconnecttest.com^$important
@@|beaz.tr.skype.com^$important
@@|api.aps.skype.com^$important
@@|options.skype.com^$important
@@|msgsearch.skype.com^$important
@@|tr.teams.microsoft.com^$important
@@|avatar.skype.com^$important
@@|b.config.skype.com^$important
@@|pipe.skype.com^$important
@@|a.config.skype.com^$important
@@|offline.microsofttranslator.com^$important
@@|tracking.epicgames.com^$important
