! Title: Macqael Hardallow
! Description: Filter composed of several Allowed domain unlocked with Adblock Plus Syntax for DNS.
! Version: 3.4
! Homepage: https://github.com/macqael/AdGuard-Home-Filters
! License: https://github.com/macqael/AdGuard-Home-Filters/blob/main/LICENSE
! Last modified: 2021-05-01
@@||googleusercontent.com^
@@||storage.googleapis.com^
@@||googlevideo.com^
@@||ggpht.com^
@@||content-storage-download.googleapis.com^
@@||docs.google.com^
@@||*._dns-sd._udp.*.in-addr.arpa^
@@||*.ip6.arpa^
@@||ipv4only.arpa^
@@||yimg.com^
@@||youtu.be^
@@||youtube-nocookie.com^
@@||youtube.com^
@@||wikihow.com^
@@||wikimedia.org^
@@||wikipedia.com^
@@||wikipedia.org^
@@||ocsp.sectigo.com^
@@||smoot.apple.com^
@@||licdn.com^
@@||pinimg.com^
@@||api.swiftype.com^
@@||services.msn.com^
@@|token.safebrowsing.apple^
@@|safebrowsing.g.aaplimg.com
@@|platform.bing.com^
@@|authenticator-azureidentity-tas.msedge.net^
@@|track.bpost.cloud^
@@|www.download.windowsupdate.com^
@@|weekend.levif.be^
@@|amcdn.msftauth.net^
@@|l.facebook.com^
@@|wordpress.com^
@@|wordpress.org^
@@|win10.ipv6.microsoft.com^
@@|r3.o.lencr.org^
@@|ocsp.pki.goog^
@@|crl.pki.goog^
@@|youtube-ui.l.google.com^
@@|pki-goog.l.google.com^
@@|googleapis.l.google.com^
@@|clients.l.google.com^
@@|www.bing.com^
@@|cdn.ravenjs.com^
@@|ajax.googleapis.com^
@@|ghs.googlehosted.com^
@@|storage.cloud.google.com^
@@|cloudstorage.gog.com^
@@|www.gstatic.com^
@@|www.google.com^
@@|csp.withgoogle.com^
@@|youtubei.googleapis.com^
@@|video.google.com^
@@|upload.wikimedia.org^
@@|znn6.mjt.lu^
@@|update.videolan.org^
@@||gvt1.com^
@@|apis.google.com^
@@|mtalk.google.com^
@@|www.googleapis.com^
@@|*-mtalk.google.com^
@@||aria.microsoft.com^
@@||cloudfront.net^
@@||delivery.mp.microsoft.com^
@@||gallery.vsassets.io^
@@||gallerycdn.vsassets.io^
@@||prod.do.dsp.mp.microsoft.com^
@@||settings.live.net^
@@||update.microsoft.com^
@@||wns.windows.com^
@@||ytimg.com^
@@|0.wikipedia.com^
@@|1fichier.com^
@@|ac.duckduckgo.com^
@@|account.adguard.com^
@@|acctcdn.msauth.net^
@@|acctcdn.msftauth.net^
@@|adguard.com^
@@|adl.windows.com^
@@|aka.ms^
@@|akadns.net^
@@|akamai.net^
@@|akamaiedge.net^
@@|akamaihd.net^
@@|akamaitechnologies.com^
@@|akamaized.net^
@@|albert.apple.com^
@@|alternativeto.net^
@@|amd.com^
@@|api-da.wixmp.com^
@@|api-glb.smoot.apple.com^
@@|api-m.paypal.com^
@@|api.adguard.com^
@@|api.bing.com^
@@|api.feedburner.com^
@@|api.github.com^
@@|api.live.net^
@@|api.msn.com^
@@|api.nuget.org^
@@|api.paypal.com^
@@|api.steampowered.com^
@@|api.weather.com^
@@|api1.weather.com^
@@|api2.weather.com^
@@|api3.weather.com^
@@|apis.live.net^
@@|app.vsaex.visualstudio.com^
@@|appldnld.apple.com^
@@|apple.com^
@@|appleid.apple.com^
@@|assets-cdn.github.com^
@@|assets.gitlab-static.net^
@@|assets.onestore.ms^
@@|au.download.windowsupdate.com^
@@|au.v4.download.windowsupdate.com^
@@|avatars*.githubusercontent.com^
@@|avatars0.githubusercontent.com^
@@|avatars1.githubusercontent.com^
@@|avatars2.githubusercontent.com^
@@|avatars3.githubusercontent.com^
@@|ax.init.itunes.apple.com^
@@|ax.itunes.apple.com^
@@|az667904.vo.msecnd.net^
@@|az725175.vo.msecnd.net^
@@|az764295.vo.msecnd.net^
@@|b.stats.paypal.com^
@@|b.tiles.mapbox.com^
@@|bing.com^
@@|bing.fr^
@@|browser.pipe.aria.microsoft.com^
@@|c.s-microsoft.com^
@@|c1.microsoft.com^
@@|cacerts.digicert.com^
@@|caldav.fe.apple-dns.net^
@@|caldav.icloud.com^
@@|calendars.fe.apple-dns.net^
@@|camo.githubusercontent.com^
@@|cdn.cloudflare.net^
@@|cdn.cloudflare.steamstatic.com^
@@|cdn.discordapp.com^
@@|cdn.flowplayer.com^
@@|cdn.jsdelivr.net^
@@|cdnjs.cloudflare.com^
@@|checkappexec.microsoft.com^
@@|checkout.stripe.com^
@@|choice.microsoft.com^
@@|client-download.steampowered.com^
@@|client.teamviewer.com^
@@|clientconfig.akamai.steamstatic.com^
@@|cloudflare.com^
@@|code.jquery.com^
@@|collections.md.mp.microsoft.com^
@@|collector.githubapp.com^
@@|commons.wikipedia.com^
@@|community.akamai.steamstatic.com^
@@|community.cloudflare.steamstatic.com^
@@|configuration.apple.com.akadns.net^
@@|content.cloudflare.com^
@@|creativecommons.org^
@@|crl.comodoca.com^
@@|crl.comodoca4.com^
@@|crl.entrust.net^
@@|crl.globalsign.com^
@@|crl.globalsign.net^
@@|crl.identrust.com^
@@|crl.sca1b.amazontrust.com^
@@|crl.thawte.com^
@@|crl.usertrust.com^
@@|crl.verisign.com^
@@|crl4.digicert.com^
@@|cs.wikipedia.com^
@@|ctldl.windowsupdate.com^
@@|curben.gitlab.io^
@@|cy.wikipedia.com^
@@|cy2.settings.data.microsoft.com.akadns.net^
@@|d3aqoihi2n8ty8.cloudfront.net^
@@|dash.cloudflare.com^
@@|datasert.gallery.vsassets.io^
@@|adb.oisd.nl^
@@|dc.services.visualstudio.com^
@@|developer.mozilla.org^
@@|developers.cloudflare.com^
@@|discord.com^
@@|discord.gg^
@@|discordapp.com^
@@|discussions.apple.com^
@@|displaycatalog.mp.microsoft.com^
@@|dl.delivery.mp.microsoft.com^
@@|dl.humble.com^
@@|dmd.metaservices.microsoft.com^
@@|dns.msftncsi.com^
@@|download.microsoft.com^
@@|download.visualstudio.microsoft.com^
@@|download.wikipedia.com^
@@|download.windowsupdate.com^
@@|downloads.intercomcdn.com^
@@|drive.google.com^
@@|ds.download.windowsupdate.com^
@@|duckduckgo.com^
@@|edge.microsoft.com^
@@|emdl.ws.microsoft.com^
@@|emea01.safelinks.protection.outlook.com^
@@|en.wikipedia.com^
@@|epicgames.com^
@@|epl.paypal-communication.com^
@@|eu.static.mega.co.nz^
@@|eu.vortex.data.microsoft.com.akadns.net^
@@|eu.vortex.data.microsoft.com^
@@|eu.wikipedia.com^
@@|eur01.safelinks.protection.outlook.com^
@@|eur02.safelinks.protection.outlook.com^
@@|eur03.safelinks.protection.outlook.com^
@@|eur04.safelinks.protection.outlook.com^
@@|evcs-ocsp.ws.symantec.com^
@@|evoke-windowsservices-tas.msedge.net^
@@|favorites.live.com^
@@|fe2cr.update.microsoft.com^
@@|feedbackws.icloud.com^
@@|feedly.com^
@@|fontawesome-cdn.fonticons.netdna-cdn.com^
@@|fonts.gstatic.com^
@@|fonts.intercomcdn.com^
@@|form.typeform.com^
@@|forms.office.com^
@@|fpt.microsoft.com^
@@|fr.uptodown.com^
@@|fr.wikipedia.com^
@@|frog.wix.com^
@@|fs.microsoft.com^
@@|g.live.com^
@@|g.static.mega.co.nz^
@@|gist.github.com^
@@|gist.githubusercontent.com^
@@|github-cloud.s3.amazonaws.com^
@@|github-production-release-asset-*.s3.amazonaws.com^
@@|github-production-user-asset-6210df.s3.amazonaws.com^
@@|github.com^
@@|github.io^
@@|gitlab.com^
@@|glb.paypal.com^
@@|go.microsoft.com^
@@|gog-statics.com^
@@|gog.com^
@@|graphql.epicgames.com^
@@|gs.apple.com^
@@|hash.github.com^
@@|hcaptcha.com^
@@|he.wikipedia.com^
@@|heartbeat.dm.origin.com^
@@|history.paypal.com^
@@|humblebundle.com^
@@|i.ibb.co^
@@|i.ytimg.com^
@@|i1.ytimg.com^
@@|id.wikipedia.com^
@@|images-1.discordapp.net^
@@|images-2.discordapp.net^
@@|images-ext-1.discordapp.net^
@@|images-ext-2.discordapp.net^
@@|images.discordapp.net^
@@|img-prod-cms-rt-microsoft-com.akamaized.net^
@@|img.youtube.com^
@@|in.appcenter.ms^
@@|ingame-news.ubi.com^
@@|ipv6check-http.steamcontent.com^
@@|ir.ebaystatic.com^
@@|itunes.apple.com^
@@|itunesconnect.apple.com^
@@|ja.wikipedia.com^
@@|jcmsfd.account.microsoft.com^
@@|jp.wikipedia.com^
@@|js.stripe.com^
@@|kb.adguard.com^
@@|la.wikipedia.com^
@@|letsencrypt.org^
@@|licensing.mp.microsoft.com^
@@|links.duckduckgo.com^
@@|live.com^
@@|live.github.com^
@@|local.adguard.com^
@@|login.live.com^
@@|login.microsoftonline.com^
@@|login.windows.net^
@@|logincdn.msauth.net^
@@|lu.api.mega.co.nz^
@@|lv.wikipedia.com^
@@|mail.live.com^
@@|mail.protonmail.com^
@@|mapbox.com^
@@|maps.windows.com^
@@|maxcdn.bootstrapcdn.com^
@@|media.discordapp.net^
@@|media.steampowered.com^
@@|media4.steampowered.com^
@@|mediafire.com^
@@|mega.co.nz^
@@|mega.io^
@@|mega.nz^
@@|mem.gfx.ms^
@@|microsoftonline.com^
@@|ml.wikipedia.com^
@@|mobile.paypal.com^
@@|mozilla.com^
@@|mozilla.net^
@@|mozilla.org^
@@|msedge.api.cdp.microsoft.com^
@@|msftconnecttest.com^
@@|msftncsi.com^
@@|msn.com^
@@|mucp.api.account.microsoft.com^
@@|naomy.cdntrex.com^
@@|ntp.msn.com^
@@|nz.static.mega.co.nz^
@@|oauth.live.com^
@@|ocsp.comodoca.com^
@@|ocsp.comodoca4.com^
@@|ocsp.digicert.com^
@@|ocsp.globalsign.com^
@@|ocsp.godaddy.com^
@@|ocsp.msocsp.com^
@@|ocsp.sca1b.amazontrust.com^
@@|ocsp.sectigo.com^
@@|ocsp.thawte.com^
@@|ocsp.usertrust.com^
@@|ocsp.verisign.com^
@@|ocsp*.globalsign.com^
@@|odc.officeapps.live.com^
@@|odinvzc.azureedge.net^
@@|office.com^
@@|office.net^
@@|office365.com^
@@|officeclient.microsoft.com^
@@|officehomeblobs.blob.core.windows.net^
@@|oneclient.sfx.ms^
@@|onedrive.com^
@@|onedrive.live.com^
@@|oneocsp.microsoft.com^
@@|outlook.com^
@@|outlook.live.com^
@@|outlook.office.com^
@@|outlook.office365.com^
@@|p.ebaystatic.com^
@@|p.sfx.ms^
@@|p.typekit.net^
@@|partner.microsoft.com^
@@|paymentinstruments.mp.microsoft.com^
@@|photo.plus.google.com^
@@|photos.live.com^
@@|pl.wikipedia.com^
@@|pmservices.cp.microsoft.com^
@@|policies.live.net^
@@|polyfill.io^
@@|posarprodcssservice.accesscontrol.windows.net^
@@|privacy.microsoft.com^
@@|products.office.com^
@@|pti.store.microsoft.com^
@@|purchase.mp.microsoft.com^
@@|qcz.gallery.vsassets.io^
@@|qos*.ol.epicgames.com^
@@|raw.github.com^
@@|raw.githubusercontent.com^
@@|redemptionservices.accesscontrol.windows.net^
@@|redirector.gvt1.com^
@@|reports.adguard.com^
@@|repository-images.githubusercontent.com^
@@|rg3.github.io^
@@|ris.api.iris.microsoft.com^
@@|rover.ebay.com^
@@|s.youtube.com^
@@|s.ytimg.com^
@@|s2.youtube.com^
@@|script.google.com^
@@|self.events.data.microsoft.com^
@@|service.weather.microsoft.com^
@@|settings-win.data.microsoft.com^
@@|settings.data.microsoft.com^
@@|settings.live.net^
@@|sfdataservice.microsoft.com^
@@|slscr.update.microsoft.com^
@@|smartscreen-prod.microsoft.com^
@@|smartscreen.microsoft.com^
@@|snapi.live.net^
@@|sourceforge.net^
@@|spaces.live.com^
@@|speedtest.net^
@@|spo-ring.msedge.net^
@@|spoprod-a.akamaihd.net^
@@|ssl.gstatic.com^
@@|stackexchange.com^
@@|stackoverflow.com^
@@|static-assets-prod.epicgames.com^
@@|static-assets-prod.unrealengine.com^
@@|static.a.upc.ubisoft.com^
@@|static.icloud.com^
@@|static.intercomassets.com^
@@|static.mediafire.com^
@@|static.wikia.nocookie.net^
@@|static.wixstatic.com^
@@|static*.cdn.ubi.com^
@@|static*.ubi.com^
@@|staticcdn.duckduckgo.com^
@@|statics-*.onestore.ms^
@@|status.github.com^
@@|steamcommunity.com^
@@|steamstore-a.akamaihd.net^
@@|steamuserimages-a.akamaihd.net^
@@|storage.live.com^
@@|storage.msn.com^
@@|store-images.microsoft.com^
@@|store-images.s-microsoft.com^
@@|store.apple.com^
@@|storecatalogrevocation.storequality.microsoft.com^
@@|storeedgefd.dsx.mp.microsoft.com^
@@|support.microsoft.com^
@@|sv.wikipedia.com^
@@|ta.wikipedia.com^
@@|tile-service.weather.microsoft.com^
@@|time.windows.com^
@@|token.cp.microsoft.com/^
@@|tokensit.cp.microsoft-tst.com/^
@@|tr.wikipedia.com^
@@|tsfe.trafficshaping.dsp.mp.microsoft.com^
@@|ubisoft-orbit-savegames.s3.amazonaws.com^
@@|ubistatic*-a.akamaihd.net^
@@|udomain.dl.sourceforge.net^
@@||phncdn.com^
@@|pornhub.com^
@@|www.pornhub.com^
@@|fr.pornhub.com^
@@|9hentai.ru^
@@|cdn.9hentai.ru^
@@|lewdpatcher.com^
@@|weeb.hanime.tv^
@@|player3.hanime.tv^
@@|hanime.tv^
@@|hw.hanime.tv^
@@|attachments.f95zone.to^
@@|attachments.f95zone.com^
@@|static.f95zone.to^
@@|static.f95zone.com^
@@|f95zone.to^
@@|f95zone.com^
@@|visualstudio-devdiv-c2s.msedge.net^
@@|visualstudio.com^
@@|wallet.ecom.ubi.com^
@@|user-images.githubusercontent.com^
@@|uplaypc-s-ubisoft.cdn.ubi.com^
@@|update.code.visualstudio.com^
@@|click.mlsend.com^
@@|feedproxy.google.com^
@@|edge-chat.facebook.com^
@@|sso.roularta.be^
@@|messagent.roulartamail.be^
@@|www.boulevard-voltaire.fr^
@@|www.agoravox.fr^
@@|www.breizh-info.com^
@@|link.huffingtonpost.fr^
@@|www.dreuz.info^
@@|levif.be^
@@|mail.levif.be^
@@|wcpstatic.microsoft.com^
@@|wdcp.microsoft.com^
@@|v10.events.data.microsoft.com^
@@|v20.events.data.microsoft.com^
@@|update.microsoft.com^
@@|alive.github.com^
@@|smp-device-content.apple.com^
@@|internalcheck.apple.com^
@@|radarsubmissions.apple.com^
@@|cstat.apple.com^
@@|code.visualstudio.com^
@@|metrics.icloud.com^
@@|api.mixpanel.com^
@@|m.stripe.network^
@@|stripe.network^
@@|targetemsecure.blob.core.windows.net^
@@|config.edge.skype.com^
@@|nav.smartscreen.microsoft.com^
@@|nf.smartscreen.microsoft.com^
@@|aadcdn.msauth.net^
@@|js.monitor.azure.com^
@@|fp.msedge.net^
@@|insights-collector.gog.com^
@@|www.paypal.com^
@@|stats.gc.apple.com^
@@|lightstep.medium.systems^
@@|ytimg.l.google.com^
@@|cdn.report-uri.com^
@@|stat.ripe.net^
@@|latency.discord.media^
@@|images2.imgbox.com^
@@|static.asm.skype.com^
@@|api3.cc.skype.com^
@@|activity.windows.com^
@@|consumer.entitlement.skype.com^
@@|api.asm.skype.com^
@@|people.skype.com^
@@|contacts.skype.com^
@@|www.msftconnecttest.com^
@@|beaz.tr.skype.com^
@@|api.aps.skype.com^
@@|options.skype.com^
@@|msgsearch.skype.com^
@@|tr.teams.microsoft.com^
@@|avatar.skype.com^
@@|b.config.skype.com^
@@|pipe.skype.com^
@@|a.config.skype.com^
@@|offline.microsofttranslator.com^
@@|tracking.epicgames.com^
@@|www.bvoltaire.fr^
@@|ipm.emsecure.net^
